#!/bin/bash

if [ $# -gt 0 ]
then 
	echo "No command line parameters allowed!"
else
	logged_in=$(who | cut -d ' ' -f 1 | sort -u)

	for usr in $logged_in;
	do
	IFS=: read user_name all_groups <<< "$(groups $usr)" 
		if [[ $all_groups = *"ugrad"* ]]
		then
			printf '%s ' "$user_name"
		fi
	done
fi
